name: react app to dockerhub

on:
  push:
    branches: ["main"] 

# gitaction docker hub
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#       - name: checkout code
#         uses: actions/checkout@v3

#       - name: docker build
#         uses: docker/setup-buildx-action@v3
      
#       - name: docker login 
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: image build and push
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/siat-git-action-frontend:latest


# gitaction aws s3       
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build React app using Docker
        run: |
          docker build -t react-app-builder .
          docker create --name temp-container react-app-builder
          docker cp temp-container:/front/build ./build
          docker rm temp-container

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "./build"  


      # err test
      # - name: Debug print
      #   run: echo "Distribution ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
#
#      # cloudfront 연결시 엣지로케이션 캐쉬 무효화
#      - name: Invalidate CloudFront Cache
#        uses: chetan/invalidate-cloudfront-action@v2
#        env:
#          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
#          PATHS: "/*"
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
#          AWS_REGION: ${{ secrets.AWS_REGION }}
      
      
